spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<segment>.*), /$\{segment}

        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /$\{segment}

server:
  port: 8080
